layout_spectrum: 0.6611171
typography_spectrum: 0.4237379
color:
  saturation: 0.04184186
  lightness: 0.7840809
  brandStrength: 0.8641245
  brandColors:
    - '#FFFFFF'
    - '#060605'
    - '#2B5B83'
    - '#A3A3A5'
    - '#E91F4B'
  rhythmicContrast: 0.3751293
name: simonforsythe
