name: simonforsythe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64104
title: Confessions Of An Uber Pastor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#060605'
    - '#2B5B83'
    - '#A3A3A5'
    - '#E91F4B'
  brandStrength: 0.8641245
  lightness: 0.7840809
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
